server:
  port: 8069
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?serverTimezone=UTC&useSSL=false
    username: root
    password: root
  application:  #配置服务名称
    name: websiteservice
    #配置nacos注册中心
  cloud:
    nacos:
      server-addr: localhost:8848
  main:
    banner-mode: off
logging:
  level:
    com.website: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  type-aliases-package: com.website.domain
  global-config:
    banner: off
